# Site settings
title: Gaussian Process Summer School, Melbourne, Australia 2015
email: 
description: > # this means to ignore newlines until "baseurl:"
  The 2015 Gaussian Process Summer School held at the University of Melbourne.
baseurl: "/gprs15b/" # the subpath of your site, e.g. /blog/
url: "http://gpss.cc" # the base hostname & protocol for your site
twitter_username: datascienceshef
github_username:  SheffieldML
facebook_page: gaussianprocesssummerschool

youtube:
  height: 315
  width: 560

conference:
  hosts:
  - {name: Trevor Cohn, url: "http://people.eng.unimelb.edu.au/tcohn/"}
  organizers:
  - {name: Neil Lawrence, url: "http://inverseprobability.com"}
  - {name: Trevor Cohn, url: "http://people.eng.unimelb.edu.au/tcohn/"}
  name: Gaussian Process Summer School
  location: University of Melbourne, Australia
  year: 2015
  month: February
  dates:
  - {date: 25, day: Wednesday, month: February, year: 2015}
  - {date: 26, day: Thursday, month: February, year: 2015}
  - {date: 27, day: Friday, month: February, year: 2015}
  
# Build settings
markdown: kramdown

